[2024-02-04 23:06:31,299,__main__] INFO : project starting
[2024-02-04 23:06:31,300,__main__] INFO : 金克拉，你有了吗？
[2024-02-04 23:06:31,303,http_server] INFO : http server started
[2024-02-04 23:06:31,309,livewebsocket] INFO : websocket server started
[2024-02-04 23:06:31,311,asyncio] ERROR : Task exception was never retrieved
future: <Task finished name='Task-1' coro=<http_server() done, defined at D:\home\documents\proj\ictye-live-dm\ictye-live-dm\http_server.py:111> exception=OSError(10048, "error while attempting to bind on address ('127.0.0.1', 8082): 一次只能用一個通訊端位址 (通訊協定/網路位址/連接埠)。")>
Traceback (most recent call last):
  File "D:\home\documents\proj\ictye-live-dm\ictye-live-dm\http_server.py", line 137, in http_server
    await site.start()
  File "C:\Users\north\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "C:\Users\north\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1519, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8082): 一次只能用一個通訊端位址 (通訊協定/網路位址/連接埠)。
[2024-02-04 23:06:31,321,livewebsocket] ERROR : websockets haven't started currently,because of [Errno 10048] error while attempting to bind on address ('127.0.0.1', 45466): 一次只能用一個通訊端位址 (通訊協定/網路位址/連接埠)。
[2024-02-04 23:12:08,205,__main__] INFO : project already stopped
